### ISSUE TITLE
Client-side Structure

### ISSUE THREAD

**Issue by ScotteRoberts** [extra-curricular-schooling/dev-webapi#3]
Luis and I have been discussing the atomic design structure for our client-side: 

http://bradfrost.com/blog/post/atomic-web-design/

This has a great potential of creating a strict component-based structure where everything is split into levels. Each level is used by the level above it until you reach the page where the content is shown. However, I am not sure if this can be done with our current code.

An alternative to that approach is to use the suggested article for large scale vuex applications.

https://medium.com/3yourmind/large-scale-vuex-application-structures-651e44863e2f

With this approach, we have come up with the following structure. The naming conventions are still off, but we can talk about those.
![capture](https://user-images.githubusercontent.com/17076638/37431963-fa7a3628-2793-11e8-83e1-1689f32e58dd.PNG)

**Comment by trishae** [comment]
I am all for this.  Would like to explicitly express my vote for YES (again). 

As far as what your screenshot shows, this structure makes sense.  My only question is, and its not at all a major concern, more of just out of curiosity, what would go in Main/_api if all individual features could have their own _api spaces?

Would also like to implement this sooner than later to see if we can make this work with what we have up right now.

**Comment by ScotteRoberts** [comment]
That does help. I am still considering where layouts should go. (Either in the pages folder or in each specific page folder). How about this structure?

![capture2](https://user-images.githubusercontent.com/17076638/37437549-028305c2-27ab-11e8-9238-66256b5ed13d.PNG)

**Comment by ScotteRoberts** [comment]
The problem is, we would copy files if we need re-usability. The atomic file structure approach remedies that problem.

Let me know what you guys think.

**Comment by ScotteRoberts** [comment]
I think this might be the best solution for re-usability and for associating appropriate items together. (The guy's article probably did this, but he didn't display his whole structure.)

![capture4](https://user-images.githubusercontent.com/17076638/37440762-6dd46c2a-27bb-11e8-8d4d-fb98b79a1f58.PNG)
